//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

using System.Xml.Serialization;
using System.Collections.Generic;

namespace CLDR.LocaleDataMarkupLanguage
{
	[XmlRoot(ElementName = "ldml")]
	public partial class ldml
	{
		private identity identityField;
		private object[] itemsField;
		private ldmlDraft draftField;
		private bool draftFieldSpecified;
		private localeDisplayNames localeDisplayNamesField;
		private characters charactersField;

		[XmlElement(ElementName = "identity")]
		public identity Identity
		{
			get { return this.identityField; }
			set { this.identityField = value; }
		}

		[XmlElement(ElementName = "localeDisplayNames")]
		public localeDisplayNames LocaleDisplayNames
		{
			get { return localeDisplayNamesField; }
			set { localeDisplayNamesField = value; }
		}

		[XmlElement(ElementName = "characters")]
		public characters Characters
		{
			get { return charactersField; }
			set { charactersField = value; }
		}

		[System.Xml.Serialization.XmlElementAttribute("alias", typeof(alias))]
		[System.Xml.Serialization.XmlElementAttribute("collations", typeof(collations))]
		[System.Xml.Serialization.XmlElementAttribute("contextTransforms", typeof(contextTransforms))]
		[System.Xml.Serialization.XmlElementAttribute("dates", typeof(dates))]
		[System.Xml.Serialization.XmlElementAttribute("delimiters", typeof(delimiters))]
		[System.Xml.Serialization.XmlElementAttribute("fallback", typeof(fallback))]
		[System.Xml.Serialization.XmlElementAttribute("layout", typeof(layout))]
		[System.Xml.Serialization.XmlElementAttribute("listPatterns", typeof(listPatterns))]
		[System.Xml.Serialization.XmlElementAttribute("measurement", typeof(measurement))]
		[System.Xml.Serialization.XmlElementAttribute("metadata", typeof(metadata))]
		[System.Xml.Serialization.XmlElementAttribute("numbers", typeof(numbers))]
		[System.Xml.Serialization.XmlElementAttribute("posix", typeof(posix))]
		[System.Xml.Serialization.XmlElementAttribute("rbnf", typeof(rbnf))]
		[System.Xml.Serialization.XmlElementAttribute("references", typeof(references))]
		[System.Xml.Serialization.XmlElementAttribute("segmentations", typeof(segmentations))]
		[System.Xml.Serialization.XmlElementAttribute("special", typeof(special))]
		[System.Xml.Serialization.XmlElementAttribute("units", typeof(units))]
		public object[] Items
		{
			get { return this.itemsField; }
			set { this.itemsField = value; }
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ldmlDraft draft
		{
			get { return this.draftField; }
			set { this.draftField = value; }
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool draftSpecified
		{
			get { return this.draftFieldSpecified; }
			set { this.draftFieldSpecified = value; }
		}
	}
}